export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
export const GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_ERROR = 'GET_TOURNAMENTS_ERROR';
export const CLEAR_TOURNAMENTS = 'CLEAR_TOURNAMENTS';